substitutions:
# Projekt Informationen
  namespace: "3dp"
  esp_project: "filamentspoolscale"
  esp_project_name: "Filament Spool Scale"
  esp_project_version: '2026.02.001a'
  device_comment: "Filament-Waage für Spoolman mit NFC Reader und Ender3 Display"

# Spoolman IP
#  spoolman_ip: ""
  
# Wifi-Secrets
#  wifi_ssid: "" 
#  wifi_password: ""
#  ota_password: ""

# Pins für dein Setup
  status_led_pin: GPIO02
  spi_clk_pin: GPIO18
  spi_mosi_pin: GPIO23
  display_cs_pin: GPIO17
  rotary_enc_a_pin: GPIO32
  rotary_enc_b_pin: GPIO33
  rotary_enc_btn_pin: GPIO19
  buzzer_pin: GPIO16 
  hx711_dout_pin: GPIO21
  hx711_clk_pin: GPIO22
  i2c_sda_pin: GPIO13
  i2c_scl_pin: GPIO14
  stepper_step_pin: GPIO25
  stepper_dir_pin: GPIO26
  runout_pin: GPIO27
  poti_pin: GPIO34
  winder_connection_pin: GPIO05

esphome:
  project:
    name: ${namespace}.${esp_project}
    version: ${esp_project_version}
    on_update: 
      then:  
  name: ${esp_project}
  friendly_name: ${esp_project_name}
  comment: ${device_comment}
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: components 
    components: [ scale_logic ]
    
scale_logic:

# From Scale V3 - Via Gemini to ESPHome
globals:
  - id: app_state
    type: int
    initial_value: '0' # 0: MAIN, 1: MENU_NO_TAG, etc.
    restore_value: no
  - id: menu_index
    type: int
    initial_value: '1'
    restore_value: no
  - id: current_spool_id
    type: int
    initial_value: '0'
    restore_value: yes
  - id: current_spool_tare
    type: int
    initial_value: '0'
    restore_value: yes
  - id: scale_offset
    type: float
    restore_value: yes
    initial_value: '0.0'

# Enable logging
logger:

captive_portal:

web_server:
  port: 80
  
packages:
  base: !include common/base.yaml
  scale: !include common/scale.yaml
  spoolman: !include common/spoolman.yaml
  nfc: !include common/nfc.yaml
  stepper: !include common/stepper.yaml
  winder_addon: !include common/winder_addon.yaml
  
  display: !include common/display.yaml
  controls: !include common/controls.yaml
  buzzer: !include common/buzzer.yaml
