binary_sensor:
  - platform: gpio
    pin:
      number: ${winder_connection_pin}
      mode: INPUT_PULLUP
      inverted: true
    id: addon_connected
    name: "Winder Addon Status"

time:
  - platform: homeassistant
    id: esptime

status_led:
  pin:
    number: ${status_led_pin}
    inverted: true
