# 3. Sensoren & Eingabe
sensor:
#  3.1 Rotary Encoder Drehung
  - platform: rotary_encoder
    name: "Rotary Encoder"
    id: my_encoder
    restore_mode: ALWAYS_ZERO 
    pin_a:
      number: ${rotary_enc_a_pin} #GPIO32          # R + // UP
      mode: INPUT_PULLUP
    pin_b:
      number: ${rotary_enc_b_pin} #GPIO33          # R - // DOWN
      mode: INPUT_PULLUP
    resolution: 1
    # Wir nutzen diese Trigger, um eine Variable zu steuern
    on_clockwise:
      - lambda: |-
          if (id(app_state) == 2) {
            id(current_spool_id)++;
            id(fetch_spoolman_data).execute(); // Sofort abfragen
          }
          // ... restliche Menü-Logik ...
          id(my_display).update();

    on_anticlockwise:
      - lambda: |-
          if (id(app_state) == 2) {
            if (id(current_spool_id) > 0) {
              id(current_spool_id)--;
              id(fetch_spoolman_data).execute(); // Sofort abfragen
            }
          }
          // ... restliche Menü-Logik ...
          id(my_display).update();

  # 3.3 Rotary Encoder Button
binary_sensor:
  - platform: gpio
    id: encoder_button
    name: "Encoder Button"
    pin:
      number: ${rotary_enc_btn_pin} #GPIO19          # BTN
      inverted: true
      mode: INPUT_PULLUP
    on_multi_click:
      # DOPPELKLICK
      - timing:
          - ON for at most 350ms
          - OFF for at most 350ms
          - ON for at most 350ms
        then:
          - lambda: |-
              if (id(app_state) == 2) {
                // Wenn wir im ID-Editor waren, jetzt Daten holen
                id(fetch_spoolman_data).execute();
                ESP_LOGI("UI", "ID #%d ausgewählt, lade Daten...", id(current_spool_id));
              }
              // Zurück zur Waage
              id(app_state) = 0; 
              id(my_display).update();

      # EINFACHKLICK
      - timing:
          - ON for at most 350ms
          - OFF for at least 350ms
        then:
          - lambda: |-
              bool has_addon = id(addon_connected).state;
              if (id(app_state) == 0) {
                // Von der Waage ins Hauptmenü springen
                id(app_state) = 1;
                id(menu_index) = 1; 
              } 
              
              else if (id(app_state) == 1) {
              
                // Logik für das Hauptmenü (m_idx entscheidet)
                if (id(menu_index) == 1) {
                  // 1. Tarieren
                  id(scale_offset) += id(filament_scale).state;
                  id(app_state) = 0;
                } 
                
                else if (id(menu_index) == 2) {
                  // 2. ID manuell setzen (Untermenü öffnen)
                  id(app_state) = 2;
                }
                
                else if (id(menu_index) == 3) {
                  // 3. Info-Screen öffnen
                  id(app_state) = 3;
                } 
                
                else if (id(menu_index) == 4) {
                  if (has_addon) {
                    // Ab in den Winder-Screen
                    id(app_state) = 4; 
                  } else {
                    // Zurück zur Waage
                    id(app_state) = 0; 
                  }
                } else if (id(menu_index) == 5 && has_addon) {
                  // Zurück zur Waage (wenn Punkt 5 existiert)
                  id(app_state) = 0; 
                }
              }
              
              // Zusätzliche Logik für den Winder-Screen (Zustand 4)
              else if (id(app_state) == 4) {
                if (id(stepper_winder).current_position == id(stepper_winder).target_position) {
                  id(stepper_winder).set_target(1000000); 
                } else {
                  id(stepper_winder).set_target(id(stepper_winder).current_position);
                }
              }
              id(my_display).update();

      # LANGER KLICK
      - timing:
          - ON for at least 600ms
        then:
          - lambda: |-
              if (id(app_state) == 2 || id(app_state) == 3) {
                // Wenn wir in einem Untermenü sind (ID Wahl oder Info), 
                // gehen wir zurück ins Hauptmenü
                id(app_state) = 1;
                ESP_LOGI("UI", "Zurück zum Hauptmenü");
              } else {
                // Wenn wir schon im Hauptmenü (1) sind, 
                // gehen wir zurück zur Waage (0)
                id(app_state) = 0;
                ESP_LOGI("UI", "Zurück zur Waage");
              }
              id(my_display).update();
