globals:
  - id: scale_offset
    type: float
    restore_value: yes
    initial_value: '0.0'
  - id: current_spool_tare
    type: int
    restore_value: yes
    initial_value: '0'

sensor:
  - platform: hx711
    name: "Gewicht"
    id: filament_scale
    dout_pin: ${hx711_dout_pin}
    clk_pin: ${hx711_clk_pin}
    gain: 128
    update_interval: 200ms # Etwas schneller für das Kalibrieren
    unit_of_measurement: "g"
    accuracy_decimals: 1
    icon: "mdi:scale"
    filters:
      - calibrate_linear:
          # Wir definieren zwei Punkte, die weit genug auseinander liegen:
          - -171000 -> 0      # Dein aktueller Leerlauf-Wert
          - 300000 -> 3000    # Ein grober Test-Wert (3kg bei 300k Rohwert)
      - lambda: |-
          return x - id(scale_offset);
      - median:
          window_size: 15
          send_every: 1
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
    on_value:
      then:
        - sensor.template.publish:
            id: filament_weight
            state: !lambda 'return x;'
    
  - platform: template
    id: filament_weight
    name: "Filament Gewicht Display"
    unit_of_measurement: g
    accuracy_decimals: 0

text_sensor:
  - platform: homeassistant
    id: spool_tare_from_ha
    entity_id: "sensor.spoolman_spool_9_tare_weight"
    internal: true
    on_value:
      then:
        - lambda: |-
            // Wenn HA einen Wert schickt (z.B. "220"), speichern wir ihn in die Global
            if (x.length() > 0) {
              id(current_spool_tare) = atof(x.c_str());
              ESP_LOGI("NFC", "Tare-Gewicht von HA empfangen: %d g", id(current_spool_tare));
            }





